/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminCurrenciesRouteImport } from './routes/admin.currencies'
import { Route as ApiPublicZiinaWebhookRouteImport } from './routes/api/public/ziina-webhook'
import { Route as ApiPublicProductImagesSplatRouteImport } from './routes/api/public/product-images.$'
import { Route as ApiPublicHooksFetchUsdLkrRouteImport } from './routes/api/public/hooks/fetch-usd-lkr'
import { Route as ApiPublicHeroImagesSplatRouteImport } from './routes/api/public/hero-images.$'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/admin/currencies',
  path: '/admin/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZiinaWebhookRoute = ApiPublicZiinaWebhookRouteImport.update({
  id: '/api/public/ziina-webhook',
  path: '/api/public/ziina-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductImagesSplatRoute =
  ApiPublicProductImagesSplatRouteImport.update({
    id: '/api/public/product-images/$',
    path: '/api/public/product-images/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFetchUsdLkrRoute =
  ApiPublicHooksFetchUsdLkrRouteImport.update({
    id: '/api/public/hooks/fetch-usd-lkr',
    path: '/api/public/hooks/fetch-usd-lkr',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHeroImagesSplatRoute =
  ApiPublicHeroImagesSplatRouteImport.update({
    id: '/api/public/hero-images/$',
    path: '/api/public/hero-images/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/ziina-webhook': typeof ApiPublicZiinaWebhookRoute
  '/api/public/hero-images/$': typeof ApiPublicHeroImagesSplatRoute
  '/api/public/hooks/fetch-usd-lkr': typeof ApiPublicHooksFetchUsdLkrRoute
  '/api/public/product-images/$': typeof ApiPublicProductImagesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/ziina-webhook': typeof ApiPublicZiinaWebhookRoute
  '/api/public/hero-images/$': typeof ApiPublicHeroImagesSplatRoute
  '/api/public/hooks/fetch-usd-lkr': typeof ApiPublicHooksFetchUsdLkrRoute
  '/api/public/product-images/$': typeof ApiPublicProductImagesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/ziina-webhook': typeof ApiPublicZiinaWebhookRoute
  '/api/public/hero-images/$': typeof ApiPublicHeroImagesSplatRoute
  '/api/public/hooks/fetch-usd-lkr': typeof ApiPublicHooksFetchUsdLkrRoute
  '/api/public/product-images/$': typeof ApiPublicProductImagesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/forgot-password'
    | '/locations'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/admin/currencies'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipping'
    | '/checkout/return'
    | '/product/$slug'
    | '/api/public/ziina-webhook'
    | '/api/public/hero-images/$'
    | '/api/public/hooks/fetch-usd-lkr'
    | '/api/public/product-images/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/forgot-password'
    | '/locations'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/admin/currencies'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipping'
    | '/checkout/return'
    | '/product/$slug'
    | '/api/public/ziina-webhook'
    | '/api/public/hero-images/$'
    | '/api/public/hooks/fetch-usd-lkr'
    | '/api/public/product-images/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/forgot-password'
    | '/locations'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/admin/currencies'
    | '/admin/hero'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipping'
    | '/checkout/return'
    | '/product/$slug'
    | '/api/public/ziina-webhook'
    | '/api/public/hero-images/$'
    | '/api/public/hooks/fetch-usd-lkr'
    | '/api/public/product-images/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicZiinaWebhookRoute: typeof ApiPublicZiinaWebhookRoute
  ApiPublicHeroImagesSplatRoute: typeof ApiPublicHeroImagesSplatRoute
  ApiPublicHooksFetchUsdLkrRoute: typeof ApiPublicHooksFetchUsdLkrRoute
  ApiPublicProductImagesSplatRoute: typeof ApiPublicProductImagesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/admin/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ziina-webhook': {
      id: '/api/public/ziina-webhook'
      path: '/api/public/ziina-webhook'
      fullPath: '/api/public/ziina-webhook'
      preLoaderRoute: typeof ApiPublicZiinaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-images/$': {
      id: '/api/public/product-images/$'
      path: '/api/public/product-images/$'
      fullPath: '/api/public/product-images/$'
      preLoaderRoute: typeof ApiPublicProductImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fetch-usd-lkr': {
      id: '/api/public/hooks/fetch-usd-lkr'
      path: '/api/public/hooks/fetch-usd-lkr'
      fullPath: '/api/public/hooks/fetch-usd-lkr'
      preLoaderRoute: typeof ApiPublicHooksFetchUsdLkrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hero-images/$': {
      id: '/api/public/hero-images/$'
      path: '/api/public/hero-images/$'
      fullPath: '/api/public/hero-images/$'
      preLoaderRoute: typeof ApiPublicHeroImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminShippingRoute: AdminShippingRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicZiinaWebhookRoute: ApiPublicZiinaWebhookRoute,
  ApiPublicHeroImagesSplatRoute: ApiPublicHeroImagesSplatRoute,
  ApiPublicHooksFetchUsdLkrRoute: ApiPublicHooksFetchUsdLkrRoute,
  ApiPublicProductImagesSplatRoute: ApiPublicProductImagesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
